name: Publish OpenApi Spec File

on:
  repository_dispatch:
    types: [publish]

permissions:
 contents: write

jobs:
  build:
    name: Publish OpenApi Spec File
    runs-on: ubuntu-latest
    env:
      TMP_FILE: .open-api.${{ github.run_id }}-${{ github.run_attempt }}.yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Install yq
        uses: dcarbone/install-yq-action@v1.1.1
      - name: Download OAI Spec File
        run: |
          curl --fail --silent \
            -H "Authorization: token ${{ secrets.RELEASE_TOKEN }}" \
            -o $TMP_FILE \
            "${{ github.event.client_payload.url }}" 

          if [ ! -f "$TMP_FILE" ]; then
            echo "URL Download failed"
            exit 1
          fi

          title=$(yq '.info.title' "$TMP_FILE")
          version=$(yq '.info.version' "$TMP_FILE")
          filename=$(echo "$title" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
          mv $TMP_FILE specs/${filename}-${version}.yaml
      - name: Check for file changes
        id: changed-spec-files
        uses: tj-actions/changed-files@v44
        with:
          files: specs/*
      - name: Check in any changes
        uses: EndBug/add-and-commit@v9
        with:
          add: specs/
          default_author: github_actions
          token: ${{ secrets.RELEASE_TOKEN }}
          